"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from pathlib import Path
from environ import Env
import sys
import os
sys.stdout.reconfigure(encoding='utf-8')
sys.stderr.reconfigure(encoding='utf-8')
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env=Env()
# env.read_env(BASE_DIR/".env")
# SECRET_KEY =env('SECRET_KEY')



# Quick-start development settings - unsuitable for production

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-t^$!9_wtj74wnms)jbhjp(ke_-uha_jcs$89xyd5skknlsndd3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.0.163','127.0.0.1', 'localhost', '172.180.1.41', '172.180.1.57', '*']

# CORS settings for Flutter app
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://172.180.1.57:8000",
    "http://172.180.1.41:8000",
]

CORS_ALLOW_ALL_ORIGINS = True  # للتطوير فقط
CORS_ALLOW_CREDENTIALS = True

# Headers للصور والملفات
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'corsheaders',
    'mptt',
    'debug_toolbar',
    'django_filters',
    'channels',
    # 'jazzmin',
    
    # Local apps
    'core',  # إضافة core package
    'accounts',
    'stores',
    'products',
    'orders',
    'wishlist',
    'pricing',
    'reviews',  # إضافة reviews app
    'notifications',  # إضافة تطبيق الإشعارات
     'driver',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # إضافة CORS middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'
ASGI_APPLICATION = 'project.asgi.application'

# Redis Configuration
REDIS_URL = 'redis://localhost:6379/0'

# Channel Layers for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Debug Toolbar configuration
INTERNAL_IPS = [
    '127.0.0.1',
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Debug Toolbar configuration (development only)
INTERNAL_IPS = [
    '127.0.0.1',
]
DEBUG_TOOLBAR_CONFIG = {
    'INTERCEPT_REDIRECTS': False,
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,
}


AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    # 'guardian.backends.ObjectPermissionBackend',
    ]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators




AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static files configuration
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files configuration (for uploaded images) - ضروري لنظام رفع الصور
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# MIME type configuration for static files
import mimetypes
mimetypes.add_type("application/javascript", ".js", True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = "accounts.User"




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER="ahmedalrshdysend@gmail.com"
EMAIL_HOST_PASSWORD="zkohwszvtmgpviay"
DEFAULT_FROM_EMAIL="ahmedalrshdysend@gmail.com"




from django.utils.timezone import timedelta
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # For JWT-based auth
        'rest_framework.authentication.SessionAuthentication',  # For session-based auth
    ],
    'DEFAULT_PERMISSION_CLASSES': (
    #'rest_framework.permissions.AllowAny',  
    ),
  

}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=60),
    'AUTH_HEADER_TYPES': ('Bearer',), 
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}



SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"  # تحديد الـ cache الذي سيتم استخدامه للجلسات
# إعدادات Celery
# هذا يخبر Celery باستخدام Redis الذي يعمل على جهازك المحلي كوسيط للرسائل.
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# هذا يخبر Celery بتخزين نتائج المهام في نفس خادم Redis (في قاعدة بيانات مختلفة إذا أردت).
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# إعدادات أخرى موصى بها لتحسين التوافق
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Riyadh'  # المنطقة الزمنية (السعودية UTC+3) 
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60 # المهام الطويلة جداً يتم إيقافها بعد 30 دقيقة
# إعدادات Firebase (اختيارية - يتم تفعيلها عند الحاجة)
# FIREBASE_CONFIG = {
#     "type": "service_account",
#     "project_id": "your-project-id",
#     "private_key_id": "your-private-key-id",
#     "private_key": "your-private-key",
#     "client_email": "your-client-email",
#     "client_id": "your-client-id",
#     "auth_uri": "https://accounts.google.com/o/oauth2/auth",
#     "token_uri": "https://oauth2.googleapis.com/token",
#     "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
#     "client_x509_cert_url": "your-cert-url"
# }

# إعدادات الإشعارات
NOTIFICATIONS_CONFIG = {
    'ENABLE_FCM': True,  # ✅ تفعيل Firebase Cloud Messaging
    'ENABLE_EMAIL_NOTIFICATIONS': True,  # تفعيل إشعارات البريد الإلكتروني
    'ENABLE_SMS_NOTIFICATIONS': False,  # تفعيل إشعارات SMS
    'AUTO_DELETE_READ_NOTIFICATIONS_DAYS': 30,  # حذف الإشعارات المقروءة بعد 30 يوم
    'MAX_NOTIFICATIONS_PER_USER': 1000,  # الحد الأقصى للإشعارات لكل مستخدم
}
