# Generated by Django 5.2.6 on 2025-11-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="اسم القالب"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order", "طلب"),
                            ("product", "منتج"),
                            ("store", "متجر"),
                            ("promotion", "عرض"),
                            ("payment", "دفع"),
                            ("shipping", "شحن"),
                            ("review", "تقييم"),
                            ("system", "نظام"),
                        ],
                        max_length=20,
                        verbose_name="نوع الإشعار",
                    ),
                ),
                (
                    "title_template",
                    models.CharField(
                        help_text="يمكن استخدام متغيرات مثل {user_name}, {order_id}",
                        max_length=255,
                        verbose_name="قالب العنوان",
                    ),
                ),
                (
                    "body_template",
                    models.TextField(
                        help_text="يمكن استخدام متغيرات مثل {user_name}, {order_id}",
                        verbose_name="قالب المحتوى",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("normal", "عادية"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية الافتراضية",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب إشعار",
                "verbose_name_plural": "قوالب الإشعارات",
            },
        ),
        migrations.CreateModel(
            name="FCMDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_token",
                    models.TextField(
                        help_text="رمز FCM الخاص بالجهاز",
                        unique=True,
                        verbose_name="رمز التسجيل",
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[("android", "أندرويد"), ("ios", "آيفون")],
                        max_length=10,
                        verbose_name="نوع الجهاز",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="اسم الجهاز"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخر استخدام"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fcm_devices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "جهاز FCM",
                "verbose_name_plural": "أجهزة FCM",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="notificatio_user_id_6cf42c_idx",
                    ),
                    models.Index(
                        fields=["registration_token"],
                        name="notificatio_registr_5a2094_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="العنوان")),
                ("body", models.TextField(verbose_name="المحتوى")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("order", "طلب"),
                            ("product", "منتج"),
                            ("store", "متجر"),
                            ("promotion", "عرض"),
                            ("payment", "دفع"),
                            ("shipping", "شحن"),
                            ("review", "تقييم"),
                            ("system", "نظام"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="النوع",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفضة"),
                            ("normal", "عادية"),
                            ("high", "عالية"),
                            ("urgent", "عاجلة"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="الأولوية",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="بيانات إضافية بصيغة JSON",
                        verbose_name="البيانات الإضافية",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="رابط الصورة"),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="مقروء")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاريخ القراءة"
                    ),
                ),
                (
                    "related_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="معرف الطلب أو المنتج أو المتجر المرتبط بالإشعار",
                        null=True,
                        verbose_name="معرف العنصر المرتبط",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="المستخدم",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(fields=["type"], name="notificatio_type_ea918f_idx"),
                ],
            },
        ),
    ]
